### ISSUE TITLE
Bringing the repository into the modern age

### ISSUE THREAD

**Issue by i509VCB** [rust-x-bindings/xkbcommon-rs#21]
At the moment these bindings are not tested to ensure pull requests build. Probably would be a good idea to setup github actions for this.

There's also some other things such as migration to 2018 edition, running cargo fmt and resolving the clippy lints (we probably want to suppress `keysyms.rs`).

**Comment by rtbo** [comment]
what is the problem with `keysyms.rs`?

**Comment by i509VCB** [comment]
Hmm looking at it further it might be the overzealous `clippy::all` lint that is enabled.

**Comment by rtbo** [comment]
I agree, I've just removed this lint in my local repo

**Comment by rtbo** [comment]
closed by #23
