### ISSUE TITLE
New 0.5.0 beta release

### ISSUE THREAD

**Issue by i509VCB** [rust-x-bindings/xkbcommon-rs#27]
Hello, I've been working on updating Smithay's client toolkit (https://github.com/Smithay/client-toolkit/pull/223) and moved to using this crate for keymap handling.

At the moment the `beta.0` release does not match upstream with some of the changes (making `new_from_fd` unsafe and the MAP_PRIVATE behavior inside `new_from_fd`).

At some point I will need a 0.50 release proper but for now I am in no real rush for a full release.

**Comment by phisch** [comment]
@rtbo do you think you can find some time for this and #33, or is there any way we can help you out?

**Comment by rtbo** [comment]
This is done now
