### ISSUE TITLE
bug: Is `MOD_NAME_MOD3` really named `mod3`?

### ISSUE THREAD

**Issue by gabyx** [rust-x-bindings/xkbcommon-rs#49]
In [here](https://github.com/rust-x-bindings/xkbcommon-rs/blob/master/src/xkb/mod.rs#L272)
is that really correct, shouldn't it be `Mod3` ?

Maybe a comment would help, if that is a exception.

**Comment by gabyx** [comment]
You are right, to make it align with xkb's lib maybe just remove this type.

And provide 5 more consts

```rust
pub const MOD_NAME_MOD1 = "Mod1"
...
pub const MOD_NAME_MOD5 = "Mod5"
```

Can these new defitions then be used? Do they work?
(I am currently looking at `wezterm` code which uses these variables?)

**Comment by jpeeler** [comment]
mod_name_is_active seems to be case sensitive, so using the MOD_NAME_MOD3 constant simply doesn't work. I'll make a PR to change for internet points, but mostly just want it fixed.

I don't understand the distinction between the different mods as the libxkbcommon cites all of them as "[unconventional](https://github.com/xkbcommon/libxkbcommon/blob/a4f62fcd8460889baeb86c9bd5a5c64607cdf9d6/doc/keymap-format-text-v1.md?plain=1#L156)". I'm hoping that for this reason the change does not require debating.

(Original constant was added in https://github.com/rust-x-bindings/xkbcommon-rs/pull/42.)
