### ISSUE TITLE
xkb::key_get_utf8 appends a null byte to the returned String.

### ISSUE THREAD

**Issue by oshaboy** [rust-x-bindings/xkbcommon-rs#50]
This doesn't happen with the other "to_utf8" functions.

**Comment by oshaboy** [comment]
I found the bug and fixed it in #51. Turns out xkb_keysym_to_utf8 returns the length including the null terminator.

**Comment by oshaboy** [comment]
BTW you might want to have it return an Option<String> as opposed to a String. I know it's a breaking API change so I didn't do it.

**Comment by rtbo** [comment]
closed by #51 #53
