### ISSUE TITLE
new release request 

### ISSUE THREAD

**Issue by jpeeler** [rust-x-bindings/xkbcommon-rs#56]
Can a tag be made for 0.8.0? There aren't too many changes:

https://github.com/rust-x-bindings/xkbcommon-rs/compare/v0.7.0...master

0.7.0 was released Oct 1, 2023.

I asked on a [tiny PR](https://github.com/rust-x-bindings/xkbcommon-rs/pull/52) of mine, but created this issue for greater visibility. Looks like https://github.com/rust-x-bindings/xkbcommon-rs/pull/54 should be added before tagging too.

**Comment by rtbo** [comment]
done
